### ISSUE TITLE
SALib dependencies

### ISSUE THREAD

**Issue by maaren** [sanjayankur31/rpm-specs#1]
Hi,

I am interested in SALib and found your spec file. I am only stuck when I try to build python-pyscaffold. I don't think all the dependencies are in the fedora repos? I am using F29.

```
$ rpmbuild -bb python-pyscaffold.spec 
warning: Macro expanded in comment on line 39: %{py3_dist configupdater}

error: Failed build dependencies:
        python3dist(pytest) is needed by python-pyscaffold-3.1-1.fc29.noarch
        python3dist(pytest-cov) is needed by python-pyscaffold-3.1-1.fc29.noarch
        python3dist(pytest-xdist) is needed by python-pyscaffold-3.1-1.fc29.noarch
        python3dist(setuptools-scm) is needed by python-pyscaffold-3.1-1.fc29.noarch
        python3dist(sphinx) is needed by python-pyscaffold-3.1-1.fc29.noarch
        python3dist(wheel) is needed by python-pyscaffold-3.1-1.fc29.noarch
$ sudo dnf install pytest pytest-cov pytest-xdist setuptools-scm sphinx wheel 
No match for argument: pytest-cov
No match for argument: pytest-xdist
No match for argument: setuptools-scm
Package sphinx-2.2.11-9.fc29.x86_64 is already installed.
No match for argument: wheel
Error: Unable to find a match
```

Can you give me a hint please?

**Comment by sanjayankur31** [comment]
You've got to install the BuildRequires as `python3-wheel` and so on. The `%{py3_dist ...}` macro that is used in the spec file expands to those. (This is explained in the Python packaging guidelines here: https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_requires_and_buildrequires_with_standardized_names)

pyscaffold is also a WIP: https://pagure.io/neuro-sig/NeuroFedora/issue/118

These packages are part of the NeuroFedora initiative. You can get in touch us with here, and we'd be happy to help out: https://fedoraproject.org/wiki/SIGs/NeuroFedora#Communication_and_getting_help

I'll close this ticket now :)

**Comment by sanjayankur31** [comment]
SAlib is also a WIP: https://pagure.io/neuro-sig/NeuroFedora/issue/117

**Comment by maaren** [comment]
OK, thnx!
